on:
  push:

env:
  package_name: wall-map-search

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x
      - name: Build
        run: npm install && npm run build

      - name: Pack
        run: cd build && tar czf ../${{ env.package_name }}.tar.gz .
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: ${{ env.package_name }}
          path: ${{ env.package_name }}.tar.gz
          if-no-files-found: error

  release:
    environment: release
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: ${{ env.package_name }}

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        id: upload_release
        with:
          files: ${{ env.package_name }}.tar.gz
          prerelease: ${{ contains(github.ref, '-') }}  # following semver spec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
